version: '2'
services:
  blog:
    container_name: hexo-blog
    build: .
    image: hexo-blog
    volumes:
      - nginx:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=doc.oasi.top
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=doc.oasi.top
      - LETSENCRYPT_EMAIL=1071956678@qq.com
volumes:
  nginx: